import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1681610799571 implements MigrationInterface {
    name = 'Init1681610799571'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`ent_user\` DROP FOREIGN KEY \`FK_5aa6123805d0c686749917371a9\``);
        await queryRunner.query(`ALTER TABLE \`ent_user\` DROP FOREIGN KEY \`FK_805aaea46df8caeefa0c957d983\``);
        await queryRunner.query(`ALTER TABLE \`ent_user\` DROP FOREIGN KEY \`FK_b11b30be03b4bb47a637b4c2e64\``);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`gender\` \`gender\` enum ('Man', 'Woman') NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`phone_number\` \`phone_number\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`address\` \`address\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`birth_date\` \`birth_date\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`avatar\` \`avatar\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`otp\` \`otp\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`token\` \`token\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`created_by_id\` \`created_by_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`updated_by_id\` \`updated_by_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`deleted_by_id\` \`deleted_by_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` DROP FOREIGN KEY \`FK_8d527f821b6eed06179894f0d5e\``);
        await queryRunner.query(`ALTER TABLE \`ent_category\` DROP FOREIGN KEY \`FK_1b3477a75857145a0ce4806d747\``);
        await queryRunner.query(`ALTER TABLE \`ent_category\` DROP FOREIGN KEY \`FK_55d4c31466635d79546c54bc121\``);
        await queryRunner.query(`ALTER TABLE \`ent_category\` DROP FOREIGN KEY \`FK_3c8cf163a87b9e099947fc66de2\``);
        await queryRunner.query(`ALTER TABLE \`ent_category\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` CHANGE \`thumbnail\` \`thumbnail\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` CHANGE \`created_by_id\` \`created_by_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` CHANGE \`updated_by_id\` \`updated_by_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` CHANGE \`deleted_by_id\` \`deleted_by_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` CHANGE \`parent_id\` \`parent_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` DROP FOREIGN KEY \`FK_bd033a7db09e866c96c05d99d1b\``);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` DROP FOREIGN KEY \`FK_4c87f70efc57995f94ef7d51a84\``);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` DROP FOREIGN KEY \`FK_521bf54f6590977eb6bdd26dcd3\``);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` DROP FOREIGN KEY \`FK_70e3a6b7fcd07c80a2472f8f3b4\``);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` CHANGE \`sku\` \`sku\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` CHANGE \`product_variant_name\` \`product_variant_name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` CHANGE \`stock_minimum\` \`stock_minimum\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` CHANGE \`expired_date\` \`expired_date\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` CHANGE \`thumbnail\` \`thumbnail\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` CHANGE \`created_by_id\` \`created_by_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` CHANGE \`updated_by_id\` \`updated_by_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` CHANGE \`deleted_by_id\` \`deleted_by_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` CHANGE \`product_id\` \`product_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` DROP FOREIGN KEY \`FK_aca2dc03934bd8111818179701c\``);
        await queryRunner.query(`ALTER TABLE \`ent_product\` DROP FOREIGN KEY \`FK_0766ed11654e02e44fd674386de\``);
        await queryRunner.query(`ALTER TABLE \`ent_product\` DROP FOREIGN KEY \`FK_f23815ed982b2d9e9c63b111429\``);
        await queryRunner.query(`ALTER TABLE \`ent_product\` DROP FOREIGN KEY \`FK_ed09acddbb99f2c378debf006b7\``);
        await queryRunner.query(`ALTER TABLE \`ent_product\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` CHANGE \`thumbnail\` \`thumbnail\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` CHANGE \`upc\` \`upc\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` CHANGE \`brand\` \`brand\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` CHANGE \`rating\` \`rating\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` CHANGE \`created_by_id\` \`created_by_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` CHANGE \`updated_by_id\` \`updated_by_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` CHANGE \`deleted_by_id\` \`deleted_by_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` CHANGE \`parent_id\` \`parent_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` DROP FOREIGN KEY \`FK_1640cad91449dfd5a9a1baa3a3b\``);
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` DROP FOREIGN KEY \`FK_c07258fcadd6cd6ce50f5a2b763\``);
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` DROP FOREIGN KEY \`FK_a040131cfca8aac239280265848\``);
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` CHANGE \`module\` \`module\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` CHANGE \`created_by_id\` \`created_by_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` CHANGE \`updated_by_id\` \`updated_by_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` CHANGE \`deleted_by_id\` \`deleted_by_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` ADD CONSTRAINT \`FK_5aa6123805d0c686749917371a9\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` ADD CONSTRAINT \`FK_805aaea46df8caeefa0c957d983\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` ADD CONSTRAINT \`FK_b11b30be03b4bb47a637b4c2e64\` FOREIGN KEY (\`deleted_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` ADD CONSTRAINT \`FK_8d527f821b6eed06179894f0d5e\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` ADD CONSTRAINT \`FK_1b3477a75857145a0ce4806d747\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` ADD CONSTRAINT \`FK_55d4c31466635d79546c54bc121\` FOREIGN KEY (\`deleted_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` ADD CONSTRAINT \`FK_3c8cf163a87b9e099947fc66de2\` FOREIGN KEY (\`parent_id\`) REFERENCES \`ent_category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` ADD CONSTRAINT \`FK_bd033a7db09e866c96c05d99d1b\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` ADD CONSTRAINT \`FK_4c87f70efc57995f94ef7d51a84\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` ADD CONSTRAINT \`FK_521bf54f6590977eb6bdd26dcd3\` FOREIGN KEY (\`deleted_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` ADD CONSTRAINT \`FK_70e3a6b7fcd07c80a2472f8f3b4\` FOREIGN KEY (\`product_id\`) REFERENCES \`ent_product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` ADD CONSTRAINT \`FK_aca2dc03934bd8111818179701c\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` ADD CONSTRAINT \`FK_0766ed11654e02e44fd674386de\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` ADD CONSTRAINT \`FK_f23815ed982b2d9e9c63b111429\` FOREIGN KEY (\`deleted_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` ADD CONSTRAINT \`FK_ed09acddbb99f2c378debf006b7\` FOREIGN KEY (\`parent_id\`) REFERENCES \`ent_product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` ADD CONSTRAINT \`FK_1640cad91449dfd5a9a1baa3a3b\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` ADD CONSTRAINT \`FK_c07258fcadd6cd6ce50f5a2b763\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` ADD CONSTRAINT \`FK_a040131cfca8aac239280265848\` FOREIGN KEY (\`deleted_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` DROP FOREIGN KEY \`FK_a040131cfca8aac239280265848\``);
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` DROP FOREIGN KEY \`FK_c07258fcadd6cd6ce50f5a2b763\``);
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` DROP FOREIGN KEY \`FK_1640cad91449dfd5a9a1baa3a3b\``);
        await queryRunner.query(`ALTER TABLE \`ent_product\` DROP FOREIGN KEY \`FK_ed09acddbb99f2c378debf006b7\``);
        await queryRunner.query(`ALTER TABLE \`ent_product\` DROP FOREIGN KEY \`FK_f23815ed982b2d9e9c63b111429\``);
        await queryRunner.query(`ALTER TABLE \`ent_product\` DROP FOREIGN KEY \`FK_0766ed11654e02e44fd674386de\``);
        await queryRunner.query(`ALTER TABLE \`ent_product\` DROP FOREIGN KEY \`FK_aca2dc03934bd8111818179701c\``);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` DROP FOREIGN KEY \`FK_70e3a6b7fcd07c80a2472f8f3b4\``);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` DROP FOREIGN KEY \`FK_521bf54f6590977eb6bdd26dcd3\``);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` DROP FOREIGN KEY \`FK_4c87f70efc57995f94ef7d51a84\``);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` DROP FOREIGN KEY \`FK_bd033a7db09e866c96c05d99d1b\``);
        await queryRunner.query(`ALTER TABLE \`ent_category\` DROP FOREIGN KEY \`FK_3c8cf163a87b9e099947fc66de2\``);
        await queryRunner.query(`ALTER TABLE \`ent_category\` DROP FOREIGN KEY \`FK_55d4c31466635d79546c54bc121\``);
        await queryRunner.query(`ALTER TABLE \`ent_category\` DROP FOREIGN KEY \`FK_1b3477a75857145a0ce4806d747\``);
        await queryRunner.query(`ALTER TABLE \`ent_category\` DROP FOREIGN KEY \`FK_8d527f821b6eed06179894f0d5e\``);
        await queryRunner.query(`ALTER TABLE \`ent_user\` DROP FOREIGN KEY \`FK_b11b30be03b4bb47a637b4c2e64\``);
        await queryRunner.query(`ALTER TABLE \`ent_user\` DROP FOREIGN KEY \`FK_805aaea46df8caeefa0c957d983\``);
        await queryRunner.query(`ALTER TABLE \`ent_user\` DROP FOREIGN KEY \`FK_5aa6123805d0c686749917371a9\``);
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` CHANGE \`deleted_by_id\` \`deleted_by_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` CHANGE \`updated_by_id\` \`updated_by_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` CHANGE \`created_by_id\` \`created_by_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` CHANGE \`module\` \`module\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` ADD CONSTRAINT \`FK_a040131cfca8aac239280265848\` FOREIGN KEY (\`deleted_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` ADD CONSTRAINT \`FK_c07258fcadd6cd6ce50f5a2b763\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_attachment\` ADD CONSTRAINT \`FK_1640cad91449dfd5a9a1baa3a3b\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` CHANGE \`parent_id\` \`parent_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` CHANGE \`deleted_by_id\` \`deleted_by_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` CHANGE \`updated_by_id\` \`updated_by_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` CHANGE \`created_by_id\` \`created_by_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` CHANGE \`rating\` \`rating\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` CHANGE \`brand\` \`brand\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` CHANGE \`upc\` \`upc\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` CHANGE \`thumbnail\` \`thumbnail\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` ADD CONSTRAINT \`FK_ed09acddbb99f2c378debf006b7\` FOREIGN KEY (\`parent_id\`) REFERENCES \`ent_product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` ADD CONSTRAINT \`FK_f23815ed982b2d9e9c63b111429\` FOREIGN KEY (\`deleted_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` ADD CONSTRAINT \`FK_0766ed11654e02e44fd674386de\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_product\` ADD CONSTRAINT \`FK_aca2dc03934bd8111818179701c\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` CHANGE \`product_id\` \`product_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` CHANGE \`deleted_by_id\` \`deleted_by_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` CHANGE \`updated_by_id\` \`updated_by_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` CHANGE \`created_by_id\` \`created_by_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` CHANGE \`thumbnail\` \`thumbnail\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` CHANGE \`expired_date\` \`expired_date\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` CHANGE \`stock_minimum\` \`stock_minimum\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` CHANGE \`product_variant_name\` \`product_variant_name\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` CHANGE \`sku\` \`sku\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` ADD CONSTRAINT \`FK_70e3a6b7fcd07c80a2472f8f3b4\` FOREIGN KEY (\`product_id\`) REFERENCES \`ent_product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` ADD CONSTRAINT \`FK_521bf54f6590977eb6bdd26dcd3\` FOREIGN KEY (\`deleted_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` ADD CONSTRAINT \`FK_4c87f70efc57995f94ef7d51a84\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_inventory\` ADD CONSTRAINT \`FK_bd033a7db09e866c96c05d99d1b\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` CHANGE \`parent_id\` \`parent_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` CHANGE \`deleted_by_id\` \`deleted_by_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` CHANGE \`updated_by_id\` \`updated_by_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` CHANGE \`created_by_id\` \`created_by_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` CHANGE \`thumbnail\` \`thumbnail\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` ADD CONSTRAINT \`FK_3c8cf163a87b9e099947fc66de2\` FOREIGN KEY (\`parent_id\`) REFERENCES \`ent_category\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` ADD CONSTRAINT \`FK_55d4c31466635d79546c54bc121\` FOREIGN KEY (\`deleted_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` ADD CONSTRAINT \`FK_1b3477a75857145a0ce4806d747\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_category\` ADD CONSTRAINT \`FK_8d527f821b6eed06179894f0d5e\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`deleted_by_id\` \`deleted_by_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`updated_by_id\` \`updated_by_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`created_by_id\` \`created_by_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`token\` \`token\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`otp\` \`otp\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`avatar\` \`avatar\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`birth_date\` \`birth_date\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`address\` \`address\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`phone_number\` \`phone_number\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`gender\` \`gender\` enum ('Man', 'Woman') NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` CHANGE \`deleted_at\` \`deleted_at\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` ADD CONSTRAINT \`FK_b11b30be03b4bb47a637b4c2e64\` FOREIGN KEY (\`deleted_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` ADD CONSTRAINT \`FK_805aaea46df8caeefa0c957d983\` FOREIGN KEY (\`updated_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ent_user\` ADD CONSTRAINT \`FK_5aa6123805d0c686749917371a9\` FOREIGN KEY (\`created_by_id\`) REFERENCES \`ent_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
